sudo: required
services:
  - docker

before_install:
  - docker build -t kunalhemrajani/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kunalhemrajani/react-test npm test -- --coverage

after_success:
  - docker build -t kunalhemrajani/multi-client ./client
  - docker build -t kunalhemrajani/multi-nginx ./nginx
  - docker build -t kunalhemrajani/multi-server ./server
  - docker build -t kunalhemrajani/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push kunalhemrajani/multi-client
  - docker push kunalhemrajani/multi-nginx
  - docker push kunalhemrajani/multi-server
  - docker push kunalhemrajani/multi-worker

deploy
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-624295586661
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
